version: "2"

# Tell Read the Docs to use the 'devel' branch as the default build source
defaults:
  version: devel

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/SphinxDoc/requirements.txt

sphinx:
  configuration: docs/SphinxDoc/source/conf.py

